version: '3.8'

services:
  # الخدمة الأولى: قاعدة البيانات
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_local_data:/data/db

  # الخدمة الثانية: مشروعك (الباك إند)
  backend:
    build: .
    ports:
      - "5000:5000"
    links:
      - database
    depends_on:
      - database

volumes:
  mongo_local_data: